sonar.projectKey=vdi-workspace
sonar.qualitygate.wait=false

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=resources/rc_resource.py,**/__pycache__/**

sonar.coverage.exclusions=src/login_controller.py,src/main_page_controller.py,src/leftmenu.py,src/settings_page.py,src/svg_background.py,src/icons.py,src/service_image_loader.py,src/app_card.py,src/desktop_card.py,src/profile_card.py,src/dialogs/**,src/widgets/**,src/infrastructure/i18n_manager.py,src/infrastructure/theme_manager.py,src/transport/executor.py,src/transport/tunnel.py
